name: Build Hugo Site
'on':
  pull_request:
    branches:
      - '**'
jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: latest
          extended: true
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.23.1
      - name: Build
        run: hugo
